"""Halo design tokens -> brand/tokens/tokens.json (DTCG format) + tokens.css (light + dark)."""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

BRAND = {'canvas': '#F7F7F5', 'ink': '#0A0A0A', 'signal': '#FF4405', 'signal-deep': '#C2360A',
         'signal-tint': '#FFEDE5', 'midnight': '#0F1114', 'white': '#FFFFFF'}

LIGHT = {
    'bg': '#F7F7F5', 'bg-sunken': '#F1F1EE', 'surface': '#FFFFFF', 'surface-2': '#F4F4F1', 'surface-3': '#ECECE8',
    'border': '#E6E6E1', 'border-strong': '#D5D5CF', 'hairline': 'rgba(10,10,10,0.07)',
    'text': '#0A0A0A', 'text-2': '#4B4B47', 'text-3': '#6B6B66', 'text-disabled': '#A6A6A0',
    'accent': '#FF4405', 'accent-text': '#C2360A', 'accent-tint': '#FFEDE5', 'on-accent': '#0A0A0A',
    'primary': '#0A0A0A', 'primary-hover': '#2A2A28', 'on-primary': '#FFFFFF',
    'success': '#12744A', 'success-tint': '#E6F3EC', 'warning': '#9A5B07', 'warning-tint': '#FBF1DE',
    'danger': '#C0262D', 'danger-tint': '#FBEAEA', 'info': '#1D5BD8', 'info-tint': '#E9EFFC',
    'focus': '#FF4405', 'scrim': 'rgba(15,17,20,0.38)', 'selection': 'rgba(255,68,5,0.16)',
}
DARK = {
    'bg': '#0F1114', 'bg-sunken': '#0B0C0E', 'surface': '#16181C', 'surface-2': '#1C1F24', 'surface-3': '#25282E',
    'border': '#262A30', 'border-strong': '#34383F', 'hairline': 'rgba(255,255,255,0.07)',
    'text': '#F2F2EF', 'text-2': '#C3C4C0', 'text-3': '#9B9C98', 'text-disabled': '#5E6066',
    'accent': '#FF4405', 'accent-text': '#FF6A38', 'accent-tint': 'rgba(255,68,5,0.14)', 'on-accent': '#0A0A0A',
    'primary': '#F2F2EF', 'primary-hover': '#FFFFFF', 'on-primary': '#0A0A0A',
    'success': '#4ADE80', 'success-tint': 'rgba(74,222,128,0.12)', 'warning': '#FBBF24', 'warning-tint': 'rgba(251,191,36,0.12)',
    'danger': '#F87171', 'danger-tint': 'rgba(248,113,113,0.12)', 'info': '#60A5FA', 'info-tint': 'rgba(96,165,250,0.12)',
    'focus': '#FF6A38', 'scrim': 'rgba(0,0,0,0.56)', 'selection': 'rgba(255,106,56,0.24)',
}
FONT = {'sans': "'Geist', ui-sans-serif, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
        'mono': "'Geist Mono', ui-monospace, 'SF Mono', Menlo, monospace"}
# name: (size px, line-height px, weight, tracking em)
TYPE = {
    'display-xl': (64, 64, 600, -0.04), 'display': (44, 48, 600, -0.035), 'title-1': (28, 34, 600, -0.025),
    'title-2': (21, 28, 600, -0.018), 'title-3': (17, 24, 600, -0.012), 'body-lg': (16, 24, 400, -0.008),
    'body': (14, 21, 400, -0.005), 'callout': (13, 19, 400, -0.003), 'caption': (12, 16, 500, 0.0),
    'micro': (11, 14, 600, 0.04), 'mono': (12, 16, 450, 0.0),
}
SPACE = [0, 2, 4, 6, 8, 12, 16, 20, 24, 32, 40, 48, 64, 80]
RADIUS = {'xs': 4, 'sm': 6, 'md': 8, 'lg': 12, 'xl': 16, '2xl': 22, 'full': 999}
SHADOW_L = {'1': '0 1px 2px rgba(10,10,10,0.04)', '2': '0 10px 30px -10px rgba(10,10,10,0.18), 0 2px 6px -2px rgba(10,10,10,0.06)',
            '3': '0 28px 70px -18px rgba(10,10,10,0.32), 0 6px 16px -6px rgba(10,10,10,0.10)'}
SHADOW_D = {'1': '0 1px 2px rgba(0,0,0,0.3)', '2': '0 12px 32px -8px rgba(0,0,0,0.6), 0 0 0 1px rgba(255,255,255,0.06)',
            '3': '0 30px 80px -16px rgba(0,0,0,0.7), 0 0 0 1px rgba(255,255,255,0.07)'}
MOTION = {'fast': '120ms', 'base': '200ms', 'slow': '320ms', 'page': '440ms',
          'ease': 'cubic-bezier(0.2, 0, 0, 1)', 'ease-out': 'cubic-bezier(0.16, 1, 0.3, 1)', 'ease-in': 'cubic-bezier(0.4, 0, 1, 1)'}

def dtcg():
    col = lambda d: {k: {'$value': v, '$type': 'color'} for k, v in d.items()}
    return {
        'brand': col(BRAND),
        'color': {'light': col(LIGHT), 'dark': col(DARK)},
        'font': {'family': {k: {'$value': v, '$type': 'fontFamily'} for k, v in FONT.items()}},
        'type': {k: {'$type': 'typography', '$value': {'fontFamily': '{font.family.%s}' % ('mono' if k == 'mono' else 'sans'),
                  'fontSize': '%dpx' % s, 'lineHeight': '%dpx' % lh, 'fontWeight': w, 'letterSpacing': '%sem' % t}}
                 for k, (s, lh, w, t) in TYPE.items()},
        'space': {str(i): {'$value': '%dpx' % v, '$type': 'dimension'} for i, v in enumerate(SPACE)},
        'radius': {k: {'$value': '%dpx' % v, '$type': 'dimension'} for k, v in RADIUS.items()},
        'shadow': {'light': {k: {'$value': v, '$type': 'shadow'} for k, v in SHADOW_L.items()},
                   'dark': {k: {'$value': v, '$type': 'shadow'} for k, v in SHADOW_D.items()}},
        'motion': {k: {'$value': v, '$type': 'duration' if v.endswith('ms') else 'cubicBezier'} for k, v in MOTION.items()},
    }

def css():
    L = []
    L.append('/* Halo design tokens — generated by tools/brand/tokens.py. Do not edit by hand. */')
    root = [':root {', '  color-scheme: light dark;']
    root += ['  --brand-%s: %s;' % (k, v) for k, v in BRAND.items()]
    root += ['  --font-%s: %s;' % (k, v) for k, v in FONT.items()]
    for k, (s, lh, w, t) in TYPE.items():
        root.append('  --type-%s: %s %dpx/%dpx var(--font-%s);' % (k, w, s, lh, 'mono' if k == 'mono' else 'sans'))
        root.append('  --track-%s: %sem;' % (k, t))
    root += ['  --space-%d: %dpx;' % (i, v) for i, v in enumerate(SPACE)]
    root += ['  --radius-%s: %dpx;' % (k, v) for k, v in RADIUS.items()]
    root += ['  --dur-%s: %s;' % (k, v) for k, v in MOTION.items() if v.endswith('ms')]
    root += ['  --%s: %s;' % (k, v) for k, v in MOTION.items() if not v.endswith('ms')]
    root.append('}')
    L += root
    light = ['  --%s: %s;' % (k, v) for k, v in LIGHT.items()] + ['  --shadow-%s: %s;' % (k, v) for k, v in SHADOW_L.items()]
    dark = ['  --%s: %s;' % (k, v) for k, v in DARK.items()] + ['  --shadow-%s: %s;' % (k, v) for k, v in SHADOW_D.items()]
    L += [':root, :root[data-theme="light"] {'] + light + ['}', ':root[data-theme="light"] { color-scheme: light; }']
    L += ['@media (prefers-color-scheme: dark) {', '  :root:not([data-theme="light"]) {', '    color-scheme: dark;'] + ['  ' + x for x in dark] + ['  }', '}']
    L += [':root[data-theme="dark"] {', '  color-scheme: dark;'] + dark + ['}']
    return '\n'.join(L) + '\n'

os.makedirs(os.path.join(ROOT, 'brand/tokens'), exist_ok=True)
json.dump(dtcg(), open(os.path.join(ROOT, 'brand/tokens/tokens.json'), 'w'), indent=2)
open(os.path.join(ROOT, 'brand/tokens/tokens.css'), 'w').write(css())

# contrast audit
def lum(h):
    h = h.lstrip('#'); c = [int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    c = [x / 12.92 if x <= 0.03928 else ((x + 0.055) / 1.055) ** 2.4 for x in c]
    return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]
def cr(a, b):
    la, lb = sorted([lum(a), lum(b)], reverse=True); return (la + 0.05) / (lb + 0.05)
checks = [('light', LIGHT, ['text', 'text-2', 'text-3', 'accent-text', 'success', 'warning', 'danger', 'info'], ['bg', 'surface', 'surface-2']),
          ('dark', DARK, ['text', 'text-2', 'text-3', 'accent-text', 'success', 'warning', 'danger', 'info'], ['bg', 'surface', 'surface-2'])]
out = {}
for mode, P, fgs, bgs in checks:
    for fg in fgs:
        for bg in bgs:
            r = cr(P[fg], P[bg]); out['%s %s/%s' % (mode, fg, bg)] = round(r, 2)
            if r < 4.5: print('FAIL', mode, fg, 'on', bg, round(r, 2))
out['ink on signal'] = round(cr('#0A0A0A', '#FF4405'), 2)
out['white on ink'] = round(cr('#FFFFFF', '#0A0A0A'), 2)
json.dump(out, open(os.path.join(ROOT, 'brand/tokens/contrast.json'), 'w'), indent=1)
print('tokens ok; min light', min(v for k, v in out.items() if k.startswith('light')), 'min dark', min(v for k, v in out.items() if k.startswith('dark')))
